[metadata]
name = "files"
description = "A channel to select files and directories"
requirements = ["fd", "bat"]

[source]
command = ["fd --type file --hidden --ignore --exclude '.git'"]

[preview]
command = "bat -n --color=always '{}'"

[keybindings]
shortcut = "f1"
