tap 'charmbracelet/tap'
tap 'common-fate/granted'
tap 'fluxcd/tap'
tap 'followtheprocess/tap'
tap 'go-task/tap'
tap 'goreleaser/tap'
tap 'hashicorp/tap'
tap 'homebrew/bundle'
tap 'homebrew/services'
tap 'kluctl/tap'
tap 'nao1215/tap'
tap 'taiki-e/tap'
brew 'openssl@3'
brew 'node'
brew 'action-docs'
brew 'actionlint'
brew 'xz'
brew 'atuin'
brew 'readline'
brew 'sqlite'
brew 'awscli'
brew 'bash'
brew 'bat'
brew 'carapace'
brew 'cargo-nextest'
brew 'gcc'
brew 'openblas'
brew 'checkov'
brew 'curl'
brew 'difftastic'
brew 'dust'
brew 'erdtree'
brew 'eza'
brew 'fd'
brew 'findutils'
brew 'fzf'
brew 'gdbm'
brew 'gh'
brew 'git'
brew 'gnu-sed'
brew 'gnupg'
brew 'go'
brew 'golangci-lint'
brew 'graphviz'
brew 'gum'
brew 'helm'
brew 'hugo'
brew 'hyperfine'
brew 'jq'
brew 'just'
brew 'k9s'
brew 'ko'
brew 'kubernetes-cli'
brew 'kubectx'
brew 'kustomize'
brew 'make'
brew 'marp-cli'
brew 'mas'
brew 'mdbook'
brew 'minikube'
brew 'nushell'
brew 'pandoc'
brew 'pinentry-mac'
brew 'procs'
brew 'ripgrep'
brew 'ruby'
brew 'ruff'
brew 'solargraph'
brew 'starship'
brew 'staticcheck'
brew 'stow'
brew 'syft'
brew 'terraform-docs'
brew 'tflint'
brew 'tldr'
brew 'tree'
brew 'trivy'
brew 'typos-cli'
brew 'uv'
brew 'vhs'
brew 'wget'
brew 'yq'
brew 'zig'
brew 'zls'
brew 'zoxide'
brew 'charmbracelet/tap/freeze'
brew 'common-fate/granted/granted'
brew 'fluxcd/tap/flux'
brew 'go-task/tap/go-task'
brew 'hashicorp/tap/terraform'
brew 'hashicorp/tap/terraform-ls'
brew 'kluctl/tap/kluctl'
brew 'nao1215/tap/gup'
brew 'taiki-e/tap/cargo-llvm-cov'
cask '1password-cli'
cask 'arc'
cask 'docker-desktop'
cask 'font-geist-mono'
cask 'font-geist-mono-nerd-font'
cask 'ghostty'
cask 'git-rekt'
cask 'goignore'
cask 'goreleaser'
cask 'gowc'
cask 'logi-options+'
cask 'raycast'
cask 'slack'
cask 'spok'
cask 'spotify'
cask 'tag'
cask 'txtract'
cask 'visual-studio-code'
cask 'wireshark-app'
cask 'zed'
cask 'zoom'
mas '1Password for Safari', id: 1_569_813_296
mas 'AdGuard for Safari', id: 1_440_147_259
mas 'Bear', id: 1_091_189_122
mas 'Dropover', id: 1_355_679_052
mas 'JSONPeep', id: 1_458_969_831
mas 'Keynote', id: 409_183_694
mas 'Magnet', id: 441_258_766
mas 'Noir', id: 1_592_917_505
mas 'Numbers', id: 409_203_825
mas 'Pages', id: 409_201_541
mas 'Refined GitHub', id: 1_519_867_270
mas 'Things', id: 904_280_696
mas 'WhatsApp', id: 310_633_997
