[tasks.fmt]
description = "Format all nix code"
run = "nix fmt"

[tasks.lint]
description = "Check the nix flake"
run = "nix flake check"

[tasks.update]
description = "Update flake.lock"
run = "nix flake update"
