# Common packages I want installed regardless of host
{ pkgs, inputs, ... }: {
  home.packages = with pkgs; [
    _1password-cli
    age
    aws-sam-cli
    bash
    betteralign
    container
    copier
    curl
    defuddle
    delve
    docker-language-server
    doggo
    dust
    entr
    eza
    findutils
    gcc
    ghostty-bin
    gnupg
    gnused
    gnutar
    gofumpt
    golangci-lint
    golangci-lint-langserver
    gomodifytags
    goperf
    gopls
    goreleaser
    gotools
    govulncheck
    gum
    hadolint
    httpie
    hyperfine
    inputs.zsh-patina.packages.${pkgs.stdenv.hostPlatform.system}.default
    jankyborders
    manix
    nil
    nilaway
    nixd
    nurl
    pkgsite
    procs
    shellcheck
    statix
    terraform
    terraform-docs
    terraform-ls
    tflint
    tlrc
    tokei
    tombi
    tparse
    trivy
    typos
    yamlfmt
    yq
    zsh-completions
  ];
}
