# https://github.com/karinushka/paneru/blob/main/CONFIGURATION.md

[options]
focus_follows_mouse = true
mouse_follows_focus = true
horizontal_mouse_warp = 1
animation_speed = 20
preset_column_widths = [0.50, 0.60, 0.70, 0.80, 0.90, 1.00]
window_resize_cycle = false
auto_center = true
reap_empty_workspaces = true

[bindings]
window_focus_west = "ctrl + alt - ,"
window_focus_east = "ctrl + alt - ."

window_swap_west = "cmd + ctrl + alt - ,"
window_swap_east = "cmd + ctrl + alt - ."

window_resize = "ctrl + alt - ]"
window_shrink = "ctrl + alt - ["

window_fullwidth = "ctrl + alt - '"
window_manage = "ctrl + alt - ;"

window_nextdisplay = "cmd + ctrl + alt - ]"

quit = "ctrl + alt - q"

[swipe]
deceleration = 0.4
sensitivity = 0.4
continuous = false

[swipe.gesture]
fingers_count = 3
direction = "Natural"

[decorations.inactive.dim]
opacity_night = -0.08

[windows.all]
title = ".*"
horizontal_padding = 6
vertical_padding = 0
width = 0.5

[windows.brainfm]
# BrainFM is a little floating menu bar type app
# don't try and tile it
title = ".*"
bundle_id = "com.electron.brain.fm"
floating = true

[windows.settings]
# Same with the apple system settings, doesn't
# really tile well and I only want it around
# for a few seconds to change something normally
title = ".*"
bundle_id = "com.apple.systempreferences"
floating = true
