[options]
focus_follows_mouse = true
mouse_follows_focus = true
animation_speed = 20
preset_column_widths = [0.50, 0.60, 0.70, 0.80, 0.90, 1.00]
window_resize_cycle = true
auto_center = false
reap_empty_workspaces = true

[bindings]
window_focus_west = "ctrl + alt - ,"
window_focus_east = "ctrl + alt - ."

window_swap_west = "cmd + ctrl + alt - ,"
window_swap_east = "cmd + ctrl + alt - ."

window_resize = "ctrl + alt - ]"
window_shrink = "ctrl + alt - ["

window_fullwidth = "ctrl + alt - '"
window_manage = "ctrl + alt - ;"

window_nextdisplay = "cmd + ctrl + alt - ]"

quit = "ctrl + alt - q"

[swipe]
deceleration = 0.4
sensitivity = 0.4
continuous = false

[swipe.gesture]
fingers_count = 3
direction = "Natural"

[decorations.inactive.dim]
opacity_night = -0.08

[decorations.active.border]
enabled = true
color = "#c6a0f6"
opacity = 0.9
width = 2.0
radius = "auto"

[windows.all]
title = ".*"
horizontal_padding = 6
vertical_padding = 0
width = 0.5
bindings_passhrough = []
