# general
background = '#24273a'
border_fg = '#494d64'
text_fg = '#cad3f5'
dimmed_text_fg = '#6e738d'
# input
input_text_fg = '#ed8796'
result_count_fg = '#ed8796'
# results
result_name_fg = '#8aadf4'
result_line_number_fg = '#eed49f'
result_value_fg = '#b7bdf8'
selection_bg = '#363a4f'
match_fg = '#ed8796'
# preview
preview_title_fg = '#f5a97f'
# modes
channel_mode_fg = '#f5bde6'
remote_control_mode_fg = '#a6da95'
send_to_channel_mode_fg = '#91d7e3'
remote_control_mode_bg = '#24273a'
channel_mode_bg = '#24273a'
selection_fg = '#a6da95'
