target-version = "py312"
line-length = 120

[lint]
select = [
    # https://docs.astral.sh/ruff/rules/
    "E",   # Pycodestyle errors
    "F",   # Pyflakes errors
    "W",   # Pycodestyle warnings
    "UP",  # All pyupgrade rules
    "N",   # PEP8 naming
    "I",   # Isort
    "C90", # Complexity
    "C4",  # Flake8 comprehensions
    "B",   # Flake8 bugbear
    "RUF", # Ruff specific rules
    "YTT", # Flake8 2020
    "BLE", # No blind excepts
    "PT",  # Pytest style
    "RET", # Function returns
    "SIM", # Simplify
    "ARG", # Unused arguments
    "PTH", # Use pathlib over os.path
    "PGH", # Pygrep hooks
]
unfixable = [
    "F841", # Stops ruff from "fixing" unused variables while you're still working on them
]

[lint.mccabe]
max-complexity = 15

[lint.isort]
required-imports = [ "from __future__ import annotations" ]
