# https://alacritty.org/config-alacritty.html
import = [
  "~/.config/alacritty/catppuccin-macchiato.toml",
]
live_config_reload = true
working_directory = "~/Development"

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 140, lines = 50 }
padding = { x = 10, y = 25 }
decorations = "transparent"

[font]
normal = { family = "SFMono Nerd Font", style = "Regular" }
size = 12

[cursor]
style = { shape = "Beam", blinking = "On" }
