"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 3

[palette]
white = "#CDD6F4"
red = "#F38AA8"
green = "#A6E2A1"

[[blocks]]
alignment = "left"
type = "prompt"

[[blocks.segments]]
foreground = "#E06C75"
style = "plain"
template = "root <p:white>in</> "
type = "root"

[[blocks.segments]]
foreground = "#6BD7CA"
style = "plain"
template = "{{ .Path }} "
type = "path"

[blocks.segments.properties]
style = "folder"

[[blocks.segments]]
foreground = "#C678DD"
style = "plain"
template = "<p:white>on {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}</>{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} "
type = "git"

[blocks.segments.properties]
fetch_status = true
branch_max_length = 25
fetch_upstream_icon = true

[[blocks.segments]]
foreground = "#89DCEB"
style = "plain"
template = "<p:white>via</>  {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }} "
type = "node"

[[blocks.segments]]
type = "go"
style = "plain"
foreground = "#89DCEB"
template = "<p:white>via</> ﳑ v{{ .Full }} "

[blocks.segments.properties]
fetch_version = true

[[blocks.segments]]
type = "python"
style = "plain"
foreground = "#FDE1A8"
template = "<p:white>via</>  v{{ .Full }} "

[blocks.segments.properties]
fetch_version = true

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

[[blocks.segments]]
foreground_templates = ['{{ if gt .Code 0 }}p:red{{ else }}p:green{{ end }}']
style = "plain"
template = "➜ "
type = "text"
