"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 3

[[blocks]]
alignment = "left"
type = "prompt"

[[blocks.segments]]
foreground = "#E06C75"
style = "plain"
template = "root <#ffffff>in</> "
type = "root"

[[blocks.segments]]
foreground = "#55B9C4"
style = "plain"
template = "{{ .Path }} "
type = "path"

[blocks.segments.properties]
style = "folder"

[[blocks.segments]]
foreground = "#C678DD"
style = "plain"
template = "<#ffffff>on</> {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} "
type = "git"

[blocks.segments.properties]
fetch_status = true

[[blocks.segments]]
foreground = "#98C379"
style = "plain"
template = "<#ffffff>via</>  {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }} "
type = "node"

[blocks.segments.properties]
fetch_version = true

[[blocks.segments]]
foreground = "#C94A16"
style = "plain"
template = "x "
type = "status"

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

[[blocks.segments]]
foreground = "#63F08C"
style = "plain"
template = "➜ "
type = "text"
